import SwiftUI
import AppKit

// MARK: - AgentMemoryCard
// The dashboard surface for Holmes's persistent memory: what it has recorded,
// and — the part the user actually asked to see — WHICH of those rows are being
// used for the task running right now.
//
// Everything on this card is read straight out of MemoryStore's SQLite rows via
// MemoryFeed. Nothing is summarized, re-worded or generated by a model here: a
// row shows the headline that was already computed deterministically when the
// context was captured. If we don't know a row's provenance we degrade it to
// "OCR only" rather than upgrading it to "exact" — the card is the honest
// receipt for the anti-hallucination design, so it must never be the place
// where a guess gets laundered into a fact.

struct AgentMemoryCard: View {
    @State private var feed = MemoryFeed.shared
    // The subject + per-row reasons behind a subject-triggered recall. Kept
    // beside the feed rather than inside it: `feed.referenced` says WHICH rows,
    // this says WHAT asked for them and WHY each one came back.
    @State private var spotlight = RecallSpotlight.shared
    @State private var isExpanded = false
    @State private var rowsAppeared = false

    /// Collapsed shows a glanceable slice; expanded scrolls a real page of
    /// history without ever loading the whole 20k-row table into the panel.
    private static let collapsedRowCount = 6
    private static let expandedRowCount = 20

    private var visibleRows: [MemoryEvent] {
        let limit = isExpanded ? Self.expandedRowCount : Self.collapsedRowCount
        return Array(feed.recent.prefix(limit))
    }

    private var hasMoreThanCollapsed: Bool {
        feed.recent.count > Self.collapsedRowCount
    }

    /// Identity of the current re-access: which rows, recalled for which
    /// subject. Everything that has to react to "the referenced set CHANGED"
    /// keys off this string — the card's animation and the banner's `.id` — so
    /// a genuinely new recall is unmistakable while a redundant re-post of the
    /// same rows stays quiet. No timer is involved anywhere: the value changing
    /// is the whole trigger.
    private var referencedKey: String {
        feed.referenced.map { String($0.id) }.joined(separator: ",")
            + "|" + spotlight.topics.joined(separator: ",")
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            header

            if !feed.referenced.isEmpty {
                ReferencedMemoryBanner(events: feed.referenced, topics: spotlight.topics)
                    // New identity per recall: a different set of rows (or the
                    // same rows recalled for a different subject) rebuilds the
                    // banner, which re-runs both the insertion transition and
                    // the one-shot highlight decay inside it.
                    .id(referencedKey)
                    .padding(.horizontal, 12)
                    .padding(.bottom, 10)
                    .transition(.asymmetric(
                        insertion: .push(from: .top).combined(with: .opacity),
                        removal: .opacity
                    ))
            }

            Divider()
                .background(NoirColors.glassDivider)

            if feed.recent.isEmpty {
                emptyState
            } else {
                recentSection
            }

            Divider()
                .background(NoirColors.glassDivider.opacity(0.5))

            // Always visible, never silent: the user can see at a glance whether
            // what they're reading came from the DOM or from guessed pixels.
            ExtensionStatusRow()
                .padding(.horizontal, 12)
                .padding(.vertical, 8)

            Divider()
                .background(NoirColors.glassDivider.opacity(0.5))

            footer
        }
        .background(
            ZStack {
                NoirColors.glassSurface
                LinearGradient(
                    colors: [Color.white.opacity(0.05), Color.clear],
                    startPoint: .top,
                    endPoint: .center
                )
            }
        )
        .clipShape(RoundedRectangle(cornerRadius: 12))
        .glassBorder(cornerRadius: 12)
        // Drives the referenced-banner transition: MemoryFeed mutates its array
        // outside withAnimation, so the strip needs its own animation trigger to
        // slide in when a task starts drawing on memory. Keyed on the row-id set
        // (not the count) — swapping one recalled row for another is exactly the
        // moment the user needs to see something move.
        .animation(.spring(response: 0.42, dampingFraction: 0.80), value: referencedKey)
        .task {
            await feed.refresh()
            triggerRowAnimation()
        }
    }

    // MARK: Header

    private var header: some View {
        Button(action: {
            withAnimation(.spring(response: 0.38, dampingFraction: 0.78)) {
                isExpanded.toggle()
            }
            triggerRowAnimation()
            Task { await feed.refresh() }
        }) {
            HStack(spacing: 7) {
                ZStack {
                    Circle()
                        .fill(Color.white.opacity(0.07))
                        .frame(width: 22, height: 22)
                    Image(systemName: "brain")
                        .font(.system(size: 10, weight: .semibold))
                        .foregroundColor(NoirColors.iconSecondary)
                }

                Text("AGENT MEMORY")
                    .font(NoirFonts.font(size: 9, weight: .bold, design: .monospaced))
                    .foregroundColor(NoirColors.textTertiary)
                    .tracking(2)

                Spacer(minLength: 6)

                // Real row counts, straight from SELECT COUNT(*) — this is the
                // number that makes the card believable as persisted SQL.
                if feed.totalCount > 0 {
                    Text("\(MemoryFormat.count(feed.totalCount)) · \(feed.todayCount) today")
                        .font(NoirFonts.font(size: 9, weight: .regular, design: .monospaced))
                        .foregroundColor(NoirColors.textTertiary)
                        .lineLimit(1)
                }

                Image(systemName: "chevron.down")
                    .font(.system(size: 9, weight: .semibold))
                    .foregroundColor(NoirColors.textTertiary)
                    .rotationEffect(.degrees(isExpanded ? 0 : -90))
                    .animation(.spring(response: 0.30, dampingFraction: 0.72), value: isExpanded)
            }
            .padding(.horizontal, 12)
            .padding(.vertical, 11)
            .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
        .help(Self.confidenceLegend)
    }

    /// Shown on hover over the header and over every confidence dot, so the
    /// colour code is discoverable without a permanent legend eating panel space.
    static let confidenceLegend = """
    Memory confidence
    ● green — exact: read from the browser DOM or a structured field.
    ● amber — structural: read from the macOS Accessibility tree.
    ◐ gray — OCR only: read from pixels, may be wrong. Holmes will not state \
    specifics from these.
    Click to expand history.
    """

    // MARK: Recent section

    private var recentSection: some View {
        VStack(alignment: .leading, spacing: 0) {
            sectionLabel("RECENT")

            if isExpanded {
                // Bounded scroll region — the panel is only 520pt tall, so the
                // expanded history scrolls inside the card instead of pushing
                // every card below it off-screen.
                ScrollView(showsIndicators: false) {
                    rowStack
                }
                .frame(maxHeight: 232)
                .transition(.opacity)
            } else {
                rowStack
            }

            if !isExpanded && hasMoreThanCollapsed {
                HStack {
                    Spacer()
                    Text("more ↓")
                        .font(NoirFonts.font(size: 9, weight: .regular, design: .monospaced))
                        .foregroundColor(NoirColors.textPlaceholder)
                }
                .padding(.horizontal, 12)
                .padding(.top, 2)
                .padding(.bottom, 8)
            }
        }
    }

    private var rowStack: some View {
        VStack(spacing: 0) {
            ForEach(Array(visibleRows.enumerated()), id: \.element.id) { index, event in
                MemoryRowView(event: event)
                    .opacity(rowsAppeared ? 1 : 0)
                    .offset(x: rowsAppeared ? 0 : -10)
                    .animation(
                        .spring(response: 0.38, dampingFraction: 0.78)
                            .delay(Double(min(index, 8)) * 0.035),
                        value: rowsAppeared
                    )
            }
        }
        .padding(.bottom, isExpanded || !hasMoreThanCollapsed ? 8 : 0)
    }

    // MARK: Empty state

    /// No pretending. If the table is empty we say so and say what would fill it.
    private var emptyState: some View {
        HStack(alignment: .top, spacing: 7) {
            Image(systemName: "tray")
                .font(.system(size: 11, weight: .regular))
                .foregroundColor(NoirColors.textPlaceholder)
            Text("No memories yet — Holmes records what you work on once the browser extension is connected.")
                .font(NoirFonts.font(size: 11, weight: .regular, design: .default))
                .foregroundColor(NoirColors.textTertiary)
                .lineSpacing(2)
                .fixedSize(horizontal: false, vertical: true)
            Spacer(minLength: 0)
        }
        .padding(.horizontal, 12)
        .padding(.vertical, 11)
    }

    // MARK: Footer

    private var footer: some View {
        HStack(spacing: 5) {
            Image(systemName: "cylinder.split.1x2")
                .font(.system(size: 8, weight: .regular))
                .foregroundColor(NoirColors.textPlaceholder)
            Text("SQLite · ~/Library/Application Support/Holmes/memory.db")
                .font(NoirFonts.font(size: 8, weight: .regular, design: .monospaced))
                .foregroundColor(NoirColors.textPlaceholder)
                .lineLimit(1)
                .truncationMode(.middle)
            Spacer(minLength: 0)
        }
        .padding(.horizontal, 12)
        .padding(.vertical, 7)
        .help("Every row on this card is a real row in that database file. Nothing here is generated.")
    }

    // MARK: Helpers

    private func sectionLabel(_ title: String) -> some View {
        HStack(spacing: 5) {
            Text("▸")
                .font(NoirFonts.font(size: 8, weight: .bold, design: .monospaced))
                .foregroundColor(NoirColors.textPlaceholder)
            Text(title)
                .font(NoirFonts.font(size: 8, weight: .bold, design: .monospaced))
                .foregroundColor(NoirColors.textTertiary)
                .tracking(1.5)
            Spacer(minLength: 0)
        }
        .padding(.horizontal, 12)
        .padding(.top, 9)
        .padding(.bottom, 5)
    }

    /// Re-runs the staggered row entrance (same trick ActivityLog uses: reset
    /// the flag, then set it one runloop later so the animation actually fires).
    private func triggerRowAnimation() {
        rowsAppeared = false
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.05) {
            withAnimation { rowsAppeared = true }
        }
    }
}

// MARK: - ReferencedMemoryBanner
// "These specific past rows are feeding the task Holmes is doing right now."
// Accent-stroked and softly pulsing so it reads as live, not as history.
//
// A re-access must be unmistakable, so the banner says three things a plain
// list cannot:
//   • WHAT asked for these rows ("recalled for: holmes") — the subject named in
//     someone's inbound message, not the user's current screen;
//   • WHY each row came back (see RecallReason), so a bad recall is catchable;
//   • THAT it just happened — a one-shot highlight that decays on appear. The
//     caller gives this view a new `.id` per recall (see referencedKey), so a
//     new set re-runs the flash exactly once. Nothing polls.

@MainActor
struct ReferencedMemoryBanner: View {
    let events: [MemoryEvent]

    /// The subjects that triggered the recall, strongest first. Empty for the
    /// activity-keyed path (findSimilar), which is driven by what the user is
    /// doing rather than by a subject someone named — the line is hidden then
    /// rather than filled in with a guess.
    var topics: [String] = []

    @State private var pulsing = false
    @State private var settled = false

    /// Reasons resolved once, outside the ForEach, so the row builder only ever
    /// handles plain values. The recall query's own `matchedOn` wins; otherwise
    /// it is re-derived from the row's stored columns against THESE subjects —
    /// never blank-filled with something plausible.
    private var rows: [(event: MemoryEvent, matchedOn: String)] {
        let supplied = RecallSpotlight.shared.reasons
        return events.prefix(3).map { event in
            let given = supplied[event.id]?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            return (event, given.isEmpty ? RecallReason.derive(event: event, topics: topics) : given)
        }
    }

    /// "holmes" / "holmes, PR #482 +1" — what Holmes went looking for.
    private var topicsLabel: String { RecallSpotlight.label(for: topics) }

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack(spacing: 5) {
                Text("▸")
                    .font(NoirFonts.font(size: 8, weight: .bold, design: .monospaced))
                    .foregroundColor(NoirColors.textPlaceholder)
                Text("REFERENCED NOW")
                    .font(NoirFonts.font(size: 8, weight: .bold, design: .monospaced))
                    .foregroundColor(NoirColors.accent.opacity(0.75))
                    .tracking(1.5)
                Spacer(minLength: 0)
                Text("(\(events.count))")
                    .font(NoirFonts.font(size: 8, weight: .bold, design: .monospaced))
                    .foregroundColor(NoirColors.accent.opacity(0.55))
            }

            if !topicsLabel.isEmpty { recalledForLine }

            VStack(spacing: 4) {
                ForEach(rows, id: \.event.id) { row in
                    MemoryRowView(event: row.event, isReferenced: true, matchedOn: row.matchedOn)
                }
            }
            .padding(.vertical, 6)
            .padding(.horizontal, 2)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(NoirColors.accentDim)
            .clipShape(RoundedRectangle(cornerRadius: 8))
            .overlay(
                RoundedRectangle(cornerRadius: 8)
                    .stroke(NoirColors.accent.opacity(pulsing ? 0.38 : 0.20), lineWidth: 0.75)
            )
            // Subtle breathing glow — the only animated affordance on the card,
            // reserved for the one thing that is happening *right now*.
            .shadow(color: Color.white.opacity(pulsing ? 0.16 : 0.04), radius: 8)
            .animation(.easeInOut(duration: 1.6).repeatForever(autoreverses: true), value: pulsing)
            // The arrival flash: rendered hot on the first frame, then decayed
            // to nothing by the onAppear below. One shot per identity, so it
            // fires when the recalled set changes and never again.
            .overlay(
                RoundedRectangle(cornerRadius: 8)
                    .fill(Color.white.opacity(settled ? 0 : 0.20))
                    .allowsHitTesting(false)
            )
            .animation(.easeOut(duration: 0.85), value: settled)
        }
        .padding(.top, 9)
        .onAppear {
            pulsing = true
            settled = true
        }
        .help(topicsLabel.isEmpty
              ? "Holmes pulled these saved memories into the task it is working on right now."
              : "Someone named \u{201C}\(topicsLabel)\u{201D}, so Holmes searched its memory for that subject and pulled these rows into the draft.")
    }

    /// The trigger, stated plainly: a subject somebody named, not the screen.
    private var recalledForLine: some View {
        HStack(spacing: 4) {
            Image(systemName: "magnifyingglass")
                .font(.system(size: 7, weight: .bold))
                .foregroundColor(NoirColors.textPlaceholder)
            Text("recalled for:")
                .font(NoirFonts.font(size: 8, weight: .regular, design: .monospaced))
                .foregroundColor(NoirColors.textPlaceholder)
            Text(topicsLabel)
                .font(NoirFonts.font(size: 8, weight: .bold, design: .monospaced))
                .foregroundColor(NoirColors.accent.opacity(0.85))
                .lineLimit(1)
                .truncationMode(.tail)
            Spacer(minLength: 0)
        }
    }
}

// MARK: - MemoryRowView
// One persisted memory. Time · headline · provenance. Tap copies the full
// stored detail so the user can inspect exactly what Holmes kept.

struct MemoryRowView: View {
    let event: MemoryEvent
    var isReferenced: Bool = false

    /// Why this row was recalled, when it was. Empty for ordinary history rows
    /// (nothing recalled them — they are just what happened).
    var matchedOn: String = ""

    @State private var isHovered = false
    @State private var copied = false

    private var facts: MemoryRowFacts { MemoryRowFacts(event: event) }

    /// Referenced rows are dated (they're usually days old and the date is the
    /// point); recent rows are relative (they're minutes old).
    private var timeLabel: String {
        isReferenced ? MemoryFormat.shortDate(event.date) : MemoryFormat.relative(event.date)
    }

    var body: some View {
        Button(action: copyDetail) {
            HStack(alignment: .top, spacing: 8) {
                confidenceDot
                    .padding(.top, 2)

                Text(timeLabel)
                    .font(NoirFonts.font(size: 9, weight: .regular, design: .monospaced))
                    .foregroundColor(NoirColors.textTertiary)
                    .frame(width: 34, alignment: .leading)
                    .padding(.top, 1)

                VStack(alignment: .leading, spacing: 2) {
                    Text(event.summary)
                        .font(NoirFonts.font(size: 11, weight: .semibold, design: .default))
                        .foregroundColor(isHovered ? NoirColors.textPrimary : NoirColors.textSecondary)
                        .lineLimit(isReferenced ? 2 : 1)
                        .multilineTextAlignment(.leading)
                        .fixedSize(horizontal: false, vertical: true)
                        .animation(.easeInOut(duration: 0.12), value: isHovered)

                    // Why · where · how well read. The reason leads, because on
                    // a recalled row it is the thing the user has to judge: if
                    // it doesn't justify the row being here, the recall is bad
                    // and the draft built on it is bad too.
                    HStack(spacing: 4) {
                        if !matchedOn.isEmpty {
                            Text(matchedOn)
                                .font(NoirFonts.font(size: 9, weight: .bold, design: .monospaced))
                                .foregroundColor(RecallReason.isWeak(matchedOn)
                                                 ? memoryAmber
                                                 : NoirColors.accent.opacity(0.7))
                                .lineLimit(1)
                            Text("·")
                                .font(NoirFonts.font(size: 9, weight: .regular, design: .monospaced))
                                .foregroundColor(NoirColors.textPlaceholder)
                        }
                        Text(facts.provenanceLine)
                            .font(NoirFonts.font(size: 9, weight: .regular, design: .monospaced))
                            .foregroundColor(NoirColors.textPlaceholder)
                            .lineLimit(1)
                            .truncationMode(.middle)
                    }
                }

                Spacer(minLength: 0)

                if copied {
                    Text("copied")
                        .font(NoirFonts.font(size: 8, weight: .bold, design: .monospaced))
                        .foregroundColor(NoirColors.success)
                        .padding(.horizontal, 5)
                        .padding(.vertical, 2)
                        .background(NoirColors.success.opacity(0.14))
                        .clipShape(Capsule())
                        .transition(.opacity.combined(with: .scale))
                }
            }
            .padding(.horizontal, isReferenced ? 8 : 12)
            .padding(.vertical, isReferenced ? 4 : 7)
            .background(isHovered ? Color.white.opacity(0.04) : Color.clear)
            .clipShape(RoundedRectangle(cornerRadius: 6))
            .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
        .animation(.easeInOut(duration: 0.14), value: isHovered)
        .onHover { isHovered = $0 }
        .help(rowTooltip)
    }

    private var confidenceDot: some View {
        Group {
            if facts.confidence == .inferred {
                // A half-filled mark, not a dot: the shape itself says
                // "partial reading" before the colour does.
                Image(systemName: "circle.lefthalf.filled")
                    .font(.system(size: 7, weight: .bold))
                    .foregroundColor(facts.confidence.dotColor)
            } else {
                Circle()
                    .fill(facts.confidence.dotColor)
                    .frame(width: 6, height: 6)
                    .padding(.top, 2)
            }
        }
        .frame(width: 8, alignment: .center)
        .help(AgentMemoryCard.confidenceLegend)
    }

    private var rowTooltip: String {
        let detail = event.detail.isEmpty ? event.summary : event.detail
        let why: String
        if matchedOn.isEmpty {
            why = ""
        } else if RecallReason.isWeak(matchedOn) {
            why = "This row came back from the full-text search, but the subject does not appear in it literally. Check it.\n\n"
        } else {
            why = "Matched on: \(matchedOn)\n\n"
        }
        return "\(why)\(MemoryFormat.fullTimestamp(event.date))\n\(String(detail.prefix(400)))\n\nClick to copy."
    }

    private func copyDetail() {
        let payload = event.detail.isEmpty ? event.summary : event.detail
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(payload, forType: .string)

        withAnimation(.spring(response: 0.28, dampingFraction: 0.72)) { copied = true }
        Task {
            try? await Task.sleep(nanoseconds: 1_400_000_000)
            withAnimation(.easeOut(duration: 0.2)) { copied = false }
        }
    }
}

// MARK: - ExtensionStatusRow
// The honest signal. When the extension is absent Holmes is reading pixels, and
// the user is told exactly that instead of being handed confident-sounding
// guesses about a page nobody actually read.

struct ExtensionStatusRow: View {
    @State private var bridge = BrowserBridge.shared
    @State private var state: BrowserBridge.LinkState = .disconnected

    private var connected: Bool { state == .connected }

    private var label: String {
        switch state {
        case .connected: return "Browser extension connected"
        case .pageContextStale: return "Extension connected, but this tab isn't sending page context. Refresh the tab."
        case .notListening(let reason): return "Browser bridge not listening: \(reason)"
        case .disconnected: return "Browser extension not connected — context is OCR-guessed"
        }
    }

    var body: some View {
        HStack(spacing: 6) {
            Text(connected ? "●" : "○")
                .font(NoirFonts.font(size: 9, weight: .bold, design: .monospaced))
                .foregroundColor(connected ? NoirColors.success : memoryAmber)

            Text(label)
                .font(NoirFonts.font(size: 10, weight: .regular, design: .default))
                .foregroundColor(connected ? NoirColors.textSecondary : memoryAmber.opacity(0.85))
                .lineLimit(2)
                .fixedSize(horizontal: false, vertical: true)

            Spacer(minLength: 0)
        }
        .help(help)
        .task {
            // Connectivity is "did the extension post within the heartbeat
            // window", so it goes stale on the clock rather than on an event —
            // poll it, otherwise the row would keep claiming "connected" long
            // after the browser was quit.
            while !Task.isCancelled {
                state = bridge.linkState
                try? await Task.sleep(nanoseconds: 3_000_000_000)
            }
        }
    }

    private var help: String {
        switch state {
        case .connected: return Self.connectedHelp
        case .pageContextStale: return Self.staleHelp
        case .notListening, .disconnected: return Self.disconnectedHelp
        }
    }

    private static let staleHelp = """
    The extension's background worker is talking to Holmes, but the page in \
    front is not sending its contents (its content script is missing or was \
    left behind by an extension update). Refresh the tab so Holmes can read it.
    """

    private static let connectedHelp = """
    The Holmes extension is POSTing page context to localhost:5766. \
    Facts about the page are read from the DOM, so Holmes can quote them exactly.
    """

    private static let disconnectedHelp = """
    Nothing has posted to localhost:5766 recently, so Holmes is falling back to \
    OCR of your screen and will hedge instead of quoting specifics.

    To connect: in Holmes Settings ▸ Privacy, click "Open extension folder". \
    In Chrome, open Extensions ▸ Developer mode ▸ "Load unpacked" and choose \
    Downloads/Holmes Extension. Keep the folder there; Chrome uses it. \
    Pair the extension in Holmes, then reload the tab you want Holmes to read.
    """
}

// MARK: - Row provenance (deterministic — never inferred upward)

/// Display facts for one memory row, parsed out of what MemoryStore already
/// persisted. Every field here is READ, never invented: `recordLiveContext`
/// writes the LiveContext provenance into the row's detail as leading
/// "key: value" lines, and this reads those keys back literally.
///
/// The fallback direction is deliberately one-way. When provenance is missing
/// we settle on `.inferred` — the weakest claim — because a row that says
/// "exact" is a promise that Holmes read real structured text. Guessing upward
/// would reintroduce exactly the hallucination this whole design exists to stop.
private struct MemoryRowFacts {
    let site: String?
    let confidence: ContextConfidence
    let app: String

    init(event: MemoryEvent) {
        let haystack = event.detail + "\n" + event.windowTitle
        self.app = event.app

        // 0. The provenance columns, when the row has them. Rows written by
        //    recordLiveContext since the provenance migration carry the source
        //    and confidence verbatim, so there is nothing to parse or infer.
        if let stored = ContextConfidence(rawValue: event.confidence) {
            self.confidence = stored
        }
        // 1. Legacy rows: an explicit "confidence: exact" line in the detail.
        else if let raw = Self.value(forKey: "confidence", in: haystack),
                let parsed = ContextConfidence(rawValue: raw.lowercased()) {
            self.confidence = parsed
        }
        // 2. Otherwise the source implies it: DOM ⇒ exact, AX ⇒ structural.
        else if let raw = Self.value(forKey: "source", in: haystack),
                let mapped = Self.confidence(forSource: raw.lowercased()) {
            self.confidence = mapped
        }
        // 3. Otherwise a bare marker anywhere in the row.
        else if let marker = Self.markerConfidence(in: haystack.lowercased()) {
            self.confidence = marker
        }
        // 4. Unknown provenance is a guess, and is labelled as one.
        else {
            self.confidence = .inferred
        }

        self.site = event.site.isEmpty
            ? (Self.value(forKey: "site", in: haystack)
                ?? Self.host(fromURLLine: Self.value(forKey: "url", in: haystack) ?? event.url))
            : event.site
    }

    /// Second line of a row: where it came from, and how much to trust it.
    var provenanceLine: String {
        let place = site ?? (app.isEmpty ? "unknown app" : app)
        return "\(place) · \(confidence.shortLabel)"
    }

    // MARK: Parsing

    /// Finds a leading `key: value` (or `key = value`) line, case-insensitively.
    private static func value(forKey key: String, in text: String) -> String? {
        for rawLine in text.components(separatedBy: .newlines) {
            let line = rawLine.trimmingCharacters(in: .whitespaces)
            guard let sep = line.firstIndex(where: { $0 == ":" || $0 == "=" }) else { continue }
            let name = line[line.startIndex..<sep]
                .trimmingCharacters(in: CharacterSet(charactersIn: "•·-— \t"))
                .lowercased()
            guard name == key else { continue }
            let value = line[line.index(after: sep)...].trimmingCharacters(in: .whitespaces)
            if !value.isEmpty { return value }
        }
        return nil
    }

    private static func confidence(forSource source: String) -> ContextConfidence? {
        if source.contains("browser") || source.contains("extension") || source.contains("dom") {
            return .exact
        }
        if source.contains("accessibility") || source.hasPrefix("ax") {
            return .structural
        }
        if source.contains("ocr") || source.contains("none") {
            return .inferred
        }
        return nil
    }

    /// Last resort: an unlabelled provenance word somewhere in the row.
    private static func markerConfidence(in text: String) -> ContextConfidence? {
        if text.contains("ocr") { return .inferred }
        if text.contains("[exact]") { return .exact }
        if text.contains("[structural]") { return .structural }
        if text.contains("[inferred]") { return .inferred }
        return nil
    }

    /// "https://mail.google.com/mail/u/0" → "mail.google.com". Falls back to a
    /// manual strip when URL() rejects a truncated string.
    private static func host(fromURLLine line: String?) -> String? {
        guard let line, !line.isEmpty else { return nil }
        if let host = URL(string: line)?.host, !host.isEmpty { return host }
        var stripped = line
        for scheme in ["https://", "http://"] where stripped.hasPrefix(scheme) {
            stripped = String(stripped.dropFirst(scheme.count))
        }
        let host = stripped.components(separatedBy: "/").first ?? stripped
        return host.contains(".") ? host : nil
    }
}

// MARK: - Confidence presentation

// File-local so the confidence colour scale can't drift into the shared design
// system. Amber genuinely isn't in NoirColors (the Apple-glass palette is
// white/green/red/blue), but the scale needs a real middle step between
// "verified green" and "we are guessing gray".
private let memoryAmber = Color(hex: "E0A33C")

private extension ContextConfidence {
    var dotColor: Color {
        switch self {
        case .exact:      return NoirColors.success
        case .structural: return memoryAmber
        case .inferred:   return NoirColors.textTertiary
        }
    }

    /// What the row says out loud. `.inferred` never gets a word that sounds
    /// like a reading — it says the pixels were guessed at.
    var shortLabel: String {
        switch self {
        case .exact:      return "exact"
        case .structural: return "structural"
        case .inferred:   return "OCR only"
        }
    }
}

// MARK: - Formatting

private enum MemoryFormat {
    /// "1,284" — grouped so a big number reads as a big number at 9pt.
    static func count(_ value: Int) -> String {
        countFormatter.string(from: NSNumber(value: value)) ?? "\(value)"
    }

    /// "now" / "2m" / "3h" / "5d" / "Jul 19" — compact enough for a 34pt column.
    static func relative(_ date: Date, now: Date = Date()) -> String {
        let seconds = now.timeIntervalSince(date)
        if seconds < 60 { return "now" }
        if seconds < 3600 { return "\(Int(seconds / 60))m" }
        if seconds < 86_400 { return "\(Int(seconds / 3600))h" }
        if seconds < 7 * 86_400 { return "\(Int(seconds / 86_400))d" }
        return shortDate(date)
    }

    static func shortDate(_ date: Date) -> String {
        shortDateFormatter.string(from: date)
    }

    static func fullTimestamp(_ date: Date) -> String {
        fullFormatter.string(from: date)
    }

    private static let countFormatter: NumberFormatter = {
        let f = NumberFormatter()
        f.numberStyle = .decimal
        return f
    }()

    private static let shortDateFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "MMM d"
        return f
    }()

    private static let fullFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "MMM d, h:mm a"
        return f
    }()
}

#Preview {
    // The live card reads the real database (empty in previews), so the row
    // rendering is previewed against fixture rows alongside it.
    let sample: [MemoryEvent] = [
        MemoryEvent(id: 1, date: Date().addingTimeInterval(-120), kind: "context",
                    app: "Comet", windowTitle: "Inbox — Gmail", activity: "reading",
                    summary: "Reading Sarah Chen's email about the Q3 rollout",
                    detail: "source: browserExtension\nconfidence: exact\nsite: mail.google.com"),
        MemoryEvent(id: 2, date: Date().addingTimeInterval(-480), kind: "context",
                    app: "Comet", windowTitle: "PR #482", activity: "reviewing",
                    summary: "Reviewing PR #482 in holmes",
                    detail: "source: browserExtension\nconfidence: exact\nurl: https://github.com/holmes/pull/482"),
        MemoryEvent(id: 3, date: Date().addingTimeInterval(-1260), kind: "context",
                    app: "Xcode", windowTitle: "LoginView.swift", activity: "coding",
                    summary: "Working in Xcode",
                    detail: "source: ocr\nconfidence: inferred"),
    ]

    return ZStack {
        Color.black.opacity(0.55).ignoresSafeArea()

        VStack(spacing: 10) {
            AgentMemoryCard()

            VStack(alignment: .leading, spacing: 0) {
                // The subject-triggered case: someone texted "hey what is
                // holmes?", so these rows were recalled for "holmes" and each
                // says which column carried the subject.
                ReferencedMemoryBanner(events: [sample[1], sample[2]], topics: ["holmes"])
                    .padding(.horizontal, 12)
                ForEach(sample, id: \.id) { MemoryRowView(event: $0) }
                ExtensionStatusRow()
                    .padding(.horizontal, 12)
                    .padding(.vertical, 8)
            }
            .background(NoirColors.glassSurface)
            .clipShape(RoundedRectangle(cornerRadius: 12))
            .glassBorder(cornerRadius: 12)
        }
        .padding(12)
    }
    .frame(width: 380, height: 620)
}
