#!/usr/bin/env swift
// Run from any directory on macOS:
// swift holmes/scripts/generate-readme-wordmark.swift
// The SVGs contain the bundled LT Remark outlines, so GitHub needs no web font.

import CoreGraphics
import CoreText
import Foundation

let repository = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()
    .deletingLastPathComponent()
    .deletingLastPathComponent()
let fontURL = repository.appendingPathComponent("holmes/holmes/Resources/Fonts/LTRemark-Regular.otf")
guard let provider = CGDataProvider(url: fontURL as CFURL),
      let graphicsFont = CGFont(provider) else {
    fatalError("Cannot read bundled LT Remark font at \(fontURL.path)")
}
let font = CTFontCreateWithGraphicsFont(graphicsFont, 80, nil, nil)
let attributedTitle = NSAttributedString(
    string: "Holmes Local",
    attributes: [NSAttributedString.Key(kCTFontAttributeName as String): font]
)
let line = CTLineCreateWithAttributedString(attributedTitle)
let outlines = CGMutablePath()
for run in CTLineGetGlyphRuns(line) as! [CTRun] {
    let count = CTRunGetGlyphCount(run)
    var glyphs = [CGGlyph](repeating: 0, count: count)
    var positions = [CGPoint](repeating: .zero, count: count)
    CTRunGetGlyphs(run, CFRange(location: 0, length: count), &glyphs)
    CTRunGetPositions(run, CFRange(location: 0, length: count), &positions)
    for (glyph, position) in zip(glyphs, positions) {
        if let outline = CTFontCreatePathForGlyph(font, glyph, nil) {
            outlines.addPath(outline, transform: CGAffineTransform(
                translationX: position.x, y: position.y
            ))
        }
    }
}

let bounds = outlines.boundingBoxOfPath
let inset: CGFloat = 4
let width = ceil(bounds.width + inset * 2)
let height = ceil(bounds.height + inset * 2)
var transform = CGAffineTransform(a: 1, b: 0, c: 0, d: -1,
                                 tx: inset - bounds.minX, ty: inset + bounds.maxY)
guard let svgPath = outlines.copy(using: &transform) else {
    fatalError("Cannot transform wordmark outlines")
}

func number(_ value: CGFloat) -> String {
    String(format: "%.2f", locale: Locale(identifier: "en_US_POSIX"), Double(value))
}
func point(_ value: CGPoint) -> String {
    "\(number(value.x)) \(number(value.y))"
}

var commands: [String] = []
svgPath.applyWithBlock { elementPointer in
    let element = elementPointer.pointee
    switch element.type {
    case .moveToPoint:
        commands.append("M\(point(element.points[0]))")
    case .addLineToPoint:
        commands.append("L\(point(element.points[0]))")
    case .addQuadCurveToPoint:
        commands.append("Q\(point(element.points[0])) \(point(element.points[1]))")
    case .addCurveToPoint:
        commands.append("C\(point(element.points[0])) \(point(element.points[1])) \(point(element.points[2]))")
    case .closeSubpath:
        commands.append("Z")
    @unknown default:
        fatalError("Unsupported path element")
    }
}

for (theme, color) in [("light", "#121212"), ("dark", "#ebe2d1")] {
    let svg = """
    <svg xmlns="http://www.w3.org/2000/svg" width="\(Int(width))" height="\(Int(height))" viewBox="0 0 \(Int(width)) \(Int(height))" role="img" aria-labelledby="title description">
      <title id="title">Holmes Local</title>
      <desc id="description">Holmes Local in the LT Remark typeface.</desc>
      <!-- Generated by holmes/scripts/generate-readme-wordmark.swift from the bundled LT Remark font. -->
      <path fill="\(color)" d="\(commands.joined(separator: " "))"/>
    </svg>

    """
    let destination = repository.appendingPathComponent("holmes/assets/holmes-wordmark-\(theme).svg")
    try svg.write(to: destination, atomically: true, encoding: .utf8)
    print("Wrote \(destination.lastPathComponent) (\(Int(width)) × \(Int(height)))")
}
